### ISSUE TITLE
TypeError: Cannot read property 'DateAdded' of undefined

### ISSUE THREAD

**Issue by faroit** [ValeriiVasin/reading-list-to-pocket#3]
reading list export stops immediately. Probably the readling list file has some new added fields like this `DateAdded`?

```
Now opening a browser to authenticate with Pocket...
Authorized successfully...
ERROR! TypeError: Cannot read property 'DateAdded' of undefined
    at items.map.item (/usr/local/lib/node_modules/reading-list-to-pocket/lib.js:22:35)
    at Array.map (<anonymous>)
    at getReadingList (/usr/local/lib/node_modules/reading-list-to-pocket/lib.js:20:16)
    at sync (/usr/local/lib/node_modules/reading-list-to-pocket/lib.js:37:17)
    at syncLocal (/usr/local/lib/node_modules/reading-list-to-pocket/lib.js:79:10)
    at /usr/local/lib/node_modules/reading-list-to-pocket/bin/cli:114:9
    at Generator.next (<anonymous>)
    at onFulfilled (/usr/local/lib/node_modules/reading-list-to-pocket/node_modules/co/index.js:65:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

**Comment by ValeriiVasin** [comment]
Thx for posting the issue. It [looks like](https://github.com/ValeriiVasin/reading-list-to-pocket/blob/be0d56ad7778eb12cfa51feab387764eb0639a4d/lib.js#L22) the ReadingList key is not there at all in the item. It should be smth like this in xml:

```xml
<key>ReadingList</key>
<dict>
  <key>DateAdded</key>
  <date>2017-11-30T12:27:48Z</date>
  <key>PreviewText</key>
  <string>Austin Gunter "All right we've got Dan Persa and Lauri Apple from Zalando Tech. Going to talk about their journey in micro services now. Without further ado, I'll let you guys kick it off." Laurie: "Yeah." Dan: </string>
  <key>ReadingListIconURL</key>
  <string>https://www.microservices.com/wp-content/uploads/2016/07/mosaic-microservices-at-zalando.jpg</string>
</dict>
```

Tried on my machine - i can not reproduce the issue. It successfully completed on my machine. Maybe they create another version of the file for new OS's that have not updated, but clean.

What OSX version are you on? And what safari version do you use?

P.S. Since safari bookmarks file could contain sensitive information and cant be posted for debugging - you could check the way data is read [here](https://github.com/ValeriiVasin/reading-list-to-pocket/blob/be0d56ad7778eb12cfa51feab387764eb0639a4d/lib.js#L8-L30) -- what file is used, converted to xml and read. And compare to your structure.
